### ISSUE TITLE
English Dataset

### ISSUE THREAD

**Issue by aldrinc** [FreedomIntelligence/HuatuoGPT#20]
Do you guys by chance have this dataset in English?

**Comment by wabyking** [comment]
Hi, Aldrinc,


We apologize for not releasing a dataset or model in English. The reason is that we are not native English speakers and, as a result, we lack the necessary proficiency or sense to prepare a well-selected dataset. We decided to initially test our basic ideas with a Chinese dataset, but we do intend to release an English dataset in the future. The specific schedule has not been determined yet, but we will definitely pursue it.

Thanks for your interest.

Best,
Benyou
